# Sparse Matrix in Python using SciPy

There are seven available sparce matrix types:

1. csc_matrix: Compressed Sparse Column format
2. csr_matrix: Compressed Sparse Row format
3. bsr_matrix: Block Sparse Row format
4. lil_matrix: List of Lists format
5. dok_matrix: Dictionary of Keys format
6. coo_matrix: COOrdinate format (aka IJV, triplet format)
7. dia_matrix: DIAgonal format

## Sparce Matrix creation

To create a sparce matrix you can use either dok_matrix or lil_matrix classes.

## Sparce Matrix Manipulation
To perform operaton such as multiplication or inversion it's necessary to convert the matrix to either CSC or CRS. Since the lil_matrix is row bases it's recommendable to convert it to CSR for more efficient usage.

## Matrix vector product

In [32]:
import numpy as np
from numpy import array
from numpy.linalg import solve, norm
from numpy.random import rand
from scipy.sparse import csr_matrix, lil_matrix, coo_matrix
from scipy.sparse.linalg import spsolve

In [2]:
A = csr_matrix([[1,2,0], [0,0,3], [4,0,5]])
v = np.array([1,0,-1])

In [7]:
print A

  (0, 0)	1
  (0, 1)	2
  (1, 2)	3
  (2, 0)	4
  (2, 2)	5


In [8]:
print v

[ 1  0 -1]


In [10]:
# Matrix vector product using SciPy
A.dot(v)

array([ 1, -3, -1])

In [11]:
# Matrix vector product using NumPy, however all the performance advantages would be lost
np.dot(A.toarray(), v)

array([ 1, -3, -1])

## Example 1

Construct a 1000x1000 lil_matrix and add some values to it

In [22]:
# Matrix creation
A = lil_matrix((1000, 1000))
A.shape

(1000, 1000)

In [24]:
# Adding some values
A[0, :100] = rand(100)
A[1, 100:200] = A[0, :100]
A.setdiag(rand(1000))

In [25]:
# Now conver to CSR format to solve A x = b for x
A = A.tocsc()
b = rand(1000)
x = spsolve(A, b)

In [28]:
# Convert the sparse matrix to a dense matrix and solve to check that the result is the same
x_ = solve(A.toarray(), b)

In [41]:
# Now we compute the norm error to compare both results, it should be small.
err = norm(x-x_)
err < 1e-10

True

In [43]:
# Another way to compare both results.
np.allclose(x, x_)

True

## Example 2

Construct a matrix in COO format and make some operations.

In [34]:
I = array([0,3,1,0])
J = array([0,3,1,2])
V = array([4,5,7,9])
A = coo_matrix((V, (I, J)), shape=(4,4)).tocsr()

In [38]:
# Notice that the indices do not need to be sorted, they will be sorted automatically.
print A

  (0, 0)	4
  (0, 2)	9
  (1, 1)	7
  (3, 3)	5


In [40]:
# I this example, duplicated (i,j) entries are summed when converting to CSR or CSC.
I = array([0,0,1,3,1,0,0])
J = array([0,2,1,3,1,0,0])
V = array([1,1,1,1,1,1,1])
B = coo_matrix((V,(I,J)),shape=(4,4)).tocsr()
print B

  (0, 0)	3
  (0, 2)	1
  (1, 1)	2
  (3, 3)	1
